language: go
sudo: required
go:
  - 1.4
  - tip

before_install:
  - export PATH=$PATH:$TRAVIS_BUILD_DIR

install:
  - go get github.com/stretchr/testify
  - export PATH=$PATH:$TRAVIS_BUILD_DIR

notifications:
  email:
    - rakzrao81@gmail.com

script:
    - sudo cp /home/travis/gopath/src/github.com/raks81/go-acousticid/fpcalc /usr/local/bin/
    - ls -ltr /home/travis/gopath/src/github.com/raks81/go-acousticid/fpcalc
    - ls -ltr /home/travis/gopath/src/github.com/raks81/go-acousticid
    - ls -ltr /home/travis/gopath/src/github.com/raks81/go-acousticid/test.mp3
    - /home/travis/gopath/src/github.com/raks81/go-acousticid/fpcalc /home/travis/gopath/src/github.com/raks81/go-acousticid/test.mp3
    - bash -x fpcalc /home/travis/gopath/src/github.com/raks81/go-acousticid/test.mp3
    - go test
