language: go
sudo: required
go:
  - 1.4
  - tip

before_install:
  - export PATH=$PATH:$TRAVIS_BUILD_DIR

install:
  - go get github.com/stretchr/testify
  - export PATH=$PATH:$TRAVIS_BUILD_DIR

notifications:
  email:
    - rakzrao81@gmail.com

script:
    - export FPCALC_BINARY_PATH=./fpcalc64
    - go test
