language: go

go:
  - 1.4
  - tip

install:
  - go get github.com/stretchr/testify

notifications:
  email:
    - rakzrao81@gmail.com

script: export PATH=$PATH:$TRAVIS_BUILD_DIR && ls -ltr && go test
