language: go
sudo: false
go:
  - 1.4

install:
  - go get github.com/stretchr/testify
  - go get github.com/mikkyang/id3-go
  - go get github.com/op/go-logging

notifications:
  email:
    - rakzrao81@gmail.com

script:
    - export FPCALC_BINARY_PATH=./fpcalc64
    - go test
